# Generated by Django 2.2.5 on 2019-09-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190918_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='categoryAlgorithmPairs',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='emailLogins',
        ),
        migrations.DeleteModel(
            name='EmailLogin',
        ),
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
