# Generated by Django 2.2.6 on 2019-10-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_testobject_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='testobject',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
