# Generated by Django 2.2.6 on 2019-10-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_testobject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testobject',
            name='testObject',
            field=models.TextField(null=True),
        ),
    ]
