export const GET_CATALGPAIRS = "GET_CATALGPAIRS";
export const DELETE_CATALGPAIR = "DELETE_CATALGPAIR";
export const ADD_CATALGPAIR = "ADD_CATALGPAIR";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
