# Generated by Django 2.2.5 on 2019-09-13 07:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='categoryAlgorithmPair',
            new_name='categoryAlgorithmPairs',
        ),
    ]
