# Generated by Django 2.2.6 on 2019-10-31 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20191031_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtoken',
            old_name='address',
            new_name='emailAddress',
        ),
    ]
