# Generated by Django 2.2.7 on 2019-11-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
