# Generated by Django 2.2.7 on 2019-11-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_auto_20191119_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='label_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
