# Generated by Django 2.2.6 on 2019-11-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_auto_20191119_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mcw',
            field=models.TextField(null=True),
        ),
    ]
